version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
    - pip install pytest
  build:
    commands:
      - pytest tests/e2e --junit-xml=reports/e2e/results.xml
reports:
 example-report-group:
   files:
     - '**/*'
   base-directory: reports/e2e/
